/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IEp:arrowRight': typeof import('~icons/ep/arrow-right')['default']
    'IEp:fullScreen': typeof import('~icons/ep/full-screen')['default']
    'IEp:setting': typeof import('~icons/ep/setting')['default']
    'IEp:tools': typeof import('~icons/ep/tools')['default']
  }
}
