/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IEp:arrowRight': typeof import('~icons/ep/arrow-right')['default']
    'IEp:loading': typeof import('~icons/ep/loading')['default']
    'IEp:more': typeof import('~icons/ep/more')['default']
    'IEp:view': typeof import('~icons/ep/view')['default']
  }
}
