import { TableOpt } from '@orm-crud/core'

export const gfdc_auth_user: TableOpt = {
  label: '用户',
  fields: [
    { prop: 'ID' },
    { prop: 'EMP_NO' },
    { prop: 'USER_NAME' },
    { prop: 'USER_ACCOUNT' },
    { prop: 'PASSWORD' },
    { prop: 'USER_STATE', options: [{ label: '在职', value: 0 }, { label: '离职', value: 1 }] },
    { prop: 'PERSON_PHOTO' },
    { prop: 'MOBILE' },
    { prop: 'EMAIL' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
    // { label: '用户扩展', prop: 'EXTEND', relation: { table: 'gfdc_auth_user_extend', rel: '1-n' } },
    // { label: '用户角色', prop: "USER_ROLE", relation: { table: 'gfdc_auth_user_role', rel: '1-n' } },
  ],
  columns: ['EMP_NO', 'USER_NAME', 'USER_ACCOUNT', 'USER_STATE', 'USER_ROLE.ROLE', 'PERSON_PHOTO', 'MOBILE', 'EMAIL'],
  searchs: ['USER_NAME'],
  forms: ['EMP_NO', 'USER_NAME', 'USER_ACCOUNT', 'USER_STATE', 'PERSON_PHOTO', 'MOBILE', 'EMAIL'],
  map: { label: 'USER_NAME', id: 'ID' },
}

export const gfdc_auth_user_extend: TableOpt = {
  label: '用户扩展',
  fields: [
    { prop: 'ID' },
    { prop: 'USER', relation: { table: 'gfdc_auth_user', rel: 'n-1' }, inverseSide: { label: '用户扩展', prop: 'EXTEND' } },
    { prop: 'IS_MAIN_JOB' },
    { prop: 'ORG', relation: { table: 'gfdc_auth_org', rel: 'n-1' }, inverseSide: { label: '用户', prop: 'USER_EXTEND' } },
    { prop: 'POSITION_NAME' },
    { prop: 'POSITION_LAYER' },
    { prop: 'REPORT_TO' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['USER', 'IS_MAIN_JOB', 'ORG', 'POSITION_NAME', 'POSITION_LAYER', 'CREATOR', 'CREATE_TIME'],
  map: { id: 'ID' },
}

export const gfdc_auth_org: TableOpt = {
  label: '组织',
  fields: [
    { prop: 'ID' },
    { prop: 'PARENT_ID' },
    { prop: 'DEPT_NO' },
    { prop: 'DEPT_NAME' },
    { prop: 'DEPT_LAYER' },
    { prop: 'ALL_PID' },
    { prop: 'DEPT_ORDER' },
    { prop: 'DEPT_STATE' },
    { prop: 'IS_LEAF' },
    { prop: 'DEPT_DESC' },
    { prop: 'BPC_DEPT_CODE' },
    { prop: 'BPC_DEPT_NAME' },
    { prop: 'IS_COMPANY' },
    { prop: 'EHR_COMPANY_DEPT' },
    { prop: 'IS_VIRTUAL' },
    { prop: 'PARENT_NO' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
    // { prop: 'USER_EXTEND', relation: { table: 'gfdc_auth_user_extend', rel: '1-n' } },
  ],
  columns: ['DEPT_NO', 'DEPT_NAME', 'DEPT_LAYER', 'ALL_PID'],
  map: { label: 'DEPT_NAME', id: 'ID' },
}

export const gfdc_auth_role: TableOpt = {
  label: '角色',
  fields: [
    { prop: "ID" },
    { prop: "ROLE_NAME" },
    { prop: "ROLE_DESC" },
    { prop: "SYSTEM", relation: { table: 'gfdc_auth_system_info', rel: 'n-1' }, inverseSide: { label: '角色', prop: 'ROLE' } },
    { prop: "CREATOR_NO" },
    { prop: "CREATOR" },
    { prop: "CREATE_TIME" },
    { prop: "MODIFIER_NO" },
    { prop: "MODIFIER" },
    { prop: "MODIFY_TIME" },
    { prop: "DEL_FLAG" },
    { prop: "VERSION" },
    // { prop: "USER_ROLE", relation: { table: 'gfdc_auth_user_role', rel: '1-n' } },
    // { prop: 'ROLE_RESOURCE', relation: { table: 'gfdc_auth_role_resource', rel: '1-n' } },
  ],
  columns: ['ROLE_NAME', 'ROLE_DESC', 'SYSTEM', 'CREATOR', 'CREATE_TIME'],
  map: { label: 'ROLE_NAME', id: 'ID' },
}

export const gfdc_auth_user_role: TableOpt = {
  label: '_用户角色',
  fields: [
    { prop: 'ID' },
    { prop: 'USER', relation: { table: 'gfdc_auth_user', rel: 'n-1' }, inverseSide: { label: '用户角色', prop: 'USER_ROLE' } },
    { prop: 'ROLE', relation: { table: 'gfdc_auth_role', rel: 'n-1' }, inverseSide: { label: '用户角色', prop: 'USER_ROLE' } },
  ],
  middle: true,
  map: { id: 'ID' },
}

export const gfdc_auth_resource: TableOpt = {
  label: '系统资源',
  fields: [
    { prop: 'ID' },
    { prop: 'RESOURCE_NAME' },
    { prop: 'RESOURCE_CODE' },
    { prop: 'SYSTEM' },
    { prop: 'RESOURCE_URL' },
    { prop: 'RESOURCE_DESC' },
    { prop: 'RESOURCE_TYPE' },
    { prop: 'OPEN_TYPE' },
    { prop: 'EXT_URL' },
    { prop: 'EXT_PARAMS' },
    { prop: 'RESOURCE_LEVEL' },
    { prop: 'SORT_TYPE' },
    { prop: 'PARENT' },
    { prop: 'COMPONENT' },
    { prop: 'ICON_TYPE' },
    { prop: 'ICON' },
    { prop: 'IDENTIFY' },
    { prop: 'LEAF' },
    { prop: 'HIDDEN' },
    { prop: 'IF_CACHE' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
    // { prop: 'ROLE_RESOURCE', relation: { table: 'gfdc_auth_role_resource', rel: '1-n' } },
  ],
  columns: ['RESOURCE_NAME', 'RESOURCE_CODE', 'SYSTEM', 'RESOURCE_URL', 'RESOURCE_TYPE', 'OPEN_TYPE', 'EXT_URL', 'EXT_PARAMS', 'RESOURCE_LEVEL', 'PARENT', 'COMPONENT', 'ICON_TYPE', 'ICON', 'HIDDEN', 'IF_CACHE', 'CREATOR', 'CREATE_TIME'],
  forms: ['RESOURCE_NAME', 'RESOURCE_CODE', 'SYSTEM', 'RESOURCE_URL', 'RESOURCE_TYPE', 'OPEN_TYPE', 'EXT_URL', 'EXT_PARAMS', 'RESOURCE_LEVEL', 'PARENT', 'COMPONENT', 'ICON_TYPE', 'ICON', 'HIDDEN', 'IF_CACHE'],
  map: { label: 'RESOURCE_NAME', id: 'ID' },
}

export const gfdc_auth_role_resource: TableOpt = {
  label: '_角色资源',
  fields: [
    { prop: 'ID' },
    { prop: 'ROLE', relation: { table: 'gfdc_auth_role', rel: 'n-1' }, inverseSide: { label: '角色资源', prop: 'ROLE_RESOURCE' } },
    { prop: 'RESOURCE', relation: { table: 'gfdc_auth_resource', rel: 'n-1' }, inverseSide: { label: '角色资源', prop: 'ROLE_RESOURCE' } },
  ],
  middle: true,
  map: { id: 'ID' },
}

export const gfdc_auth_system_info: TableOpt = {
  label: '系统信息',
  fields: [
    { prop: 'ID' },
    { prop: 'SYSTEM_NAME' },
    { prop: 'SYSTEM_CODE' },
    { prop: 'SYSTEM_DESC' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
    // { prop: 'ROLE', relation: { table: 'gfdc_auth_role', rel: '1-n' } },
  ],
  columns: ['SYSTEM_NAME', 'SYSTEM_CODE', 'SYSTEM_DESC', 'CREATOR', 'CREATE_TIME'],
  forms: ['SYSTEM_NAME', 'SYSTEM_CODE', 'SYSTEM_DESC'],
  map: { label: 'SYSTEM_NAME', id: 'ID' },
}