import { TableOpt } from '@orm-crud/core'

export const gfdc_auth_user: TableOpt = {
  label: '用户',
  fields: [
    { prop: 'ID' },
    { label: '员工编号', prop: 'EMP_NO' },
    { label: '姓名', prop: 'USER_NAME', filter: 'contains' },
    { label: '账号', prop: 'USER_ACCOUNT' },
    { prop: 'PASSWORD' },
    { label: '状态', prop: 'USER_STATE', options: [{ label: '在职', value: 0 }, { label: '离职', value: 1 }] },
    { prop: 'PERSON_PHOTO' },
    { prop: 'MOBILE' },
    { prop: 'EMAIL' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['EMP_NO', 'USER_NAME', 'USER_ACCOUNT', 'USER_STATE', 'USER_ROLE.ROLE', 'MOBILE', 'EMAIL'],
  searchs: ['USER_NAME', 'USER_ROLE.ROLE', 'SYS_OPERATION_LOG', 'USER_STATE'],
  forms: ['EMP_NO', 'USER_NAME', 'USER_ACCOUNT', 'USER_STATE', 'PERSON_PHOTO', 'MOBILE', 'EMAIL'],
  map: { label: 'USER_NAME', id: 'ID' },
}

export const gfdc_auth_user_extend: TableOpt = {
  label: '用户扩展',
  fields: [
    { prop: 'ID' },
    { prop: 'USER', relation: { table: 'gfdc_auth_user', rel: 'n-1' }, inverseSide: { label: '用户扩展', prop: 'EXTEND' } },
    { prop: 'IS_MAIN_JOB' },
    { prop: 'ORG', relation: { table: 'gfdc_auth_org', rel: 'n-1' }, inverseSide: { label: '用户', prop: 'USER_EXTEND' } },
    { prop: 'POSITION_NAME' },
    { prop: 'POSITION_LAYER' },
    { prop: 'REPORT_TO' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['USER', 'IS_MAIN_JOB', 'ORG', 'POSITION_NAME', 'POSITION_LAYER', 'CREATOR', 'CREATE_TIME'],
  searchs: ['ORG', 'POSITION_NAME'],
  map: { id: 'ID' },
}

export const gfdc_auth_org: TableOpt = {
  label: '组织',
  fields: [
    { prop: 'ID' },
    { prop: 'PARENT_ID' },
    { prop: 'DEPT_NO' },
    { prop: 'DEPT_NAME', filter: 'contains' },
    { prop: 'DEPT_LAYER' },
    { prop: 'ALL_PID' },
    { prop: 'DEPT_ORDER' },
    { prop: 'DEPT_STATE', options: [{ label: '正常', value: 0 }, { label: '启用', value: 1 }] },
    { prop: 'IS_LEAF' },
    { prop: 'DEPT_DESC' },
    { prop: 'BPC_DEPT_CODE' },
    { prop: 'BPC_DEPT_NAME' },
    { prop: 'IS_COMPANY', options: [{ label: '否', value: 0 }, { label: '是', value: 1 }] },
    { prop: 'EHR_COMPANY_DEPT' },
    { prop: 'IS_VIRTUAL' },
    { prop: 'PARENT_NO' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['DEPT_NO', 'DEPT_NAME', 'DEPT_LAYER', 'ALL_PID', 'DEPT_STATE'],
  searchs: ['DEPT_NAME', 'DEPT_STATE'],
  map: { label: 'DEPT_NAME', id: 'ID' },
}

export const gfdc_auth_role: TableOpt = {
  label: '角色',
  fields: [
    { prop: "ID" },
    { prop: "ROLE_NAME" },
    { prop: "ROLE_DESC" },
    { prop: "SYSTEM", relation: { table: 'gfdc_auth_system_info', rel: 'n-1' }, inverseSide: { label: '角色', prop: 'ROLE' } },
    { prop: "CREATOR_NO" },
    { prop: "CREATOR" },
    { prop: "CREATE_TIME" },
    { prop: "MODIFIER_NO" },
    { prop: "MODIFIER" },
    { prop: "MODIFY_TIME" },
    { prop: "DEL_FLAG" },
    { prop: "VERSION" },
  ],
  columns: ['ROLE_NAME', 'ROLE_DESC', 'SYSTEM', 'CREATOR', 'CREATE_TIME'],
  forms: ['SYSTEM', 'ROLE_RESOURCE.RESOURCE'],
  searchs: ['SYSTEM', 'ROLE_RESOURCE.RESOURCE'],
  map: { label: 'ROLE_NAME', id: 'ID' },
}

export const gfdc_auth_user_role: TableOpt = {
  label: '_用户角色',
  fields: [
    { prop: 'ID' },
    { prop: 'USER', relation: { table: 'gfdc_auth_user', rel: 'n-1' }, inverseSide: { label: '用户角色', prop: 'USER_ROLE' } },
    { prop: 'ROLE', relation: { table: 'gfdc_auth_role', rel: 'n-1' }, inverseSide: { label: '用户角色', prop: 'USER_ROLE' } },
  ],
  columns: ['USER', 'ROLE'],
  middle: true,
  map: { id: 'ID' },
}

export const gfdc_auth_resource: TableOpt = {
  label: '菜单',
  fields: [
    { prop: 'ID' },
    { prop: 'RESOURCE_NAME', filter: 'contains' },
    { prop: 'RESOURCE_CODE' },
    { prop: 'SYSTEM', relation: { table: 'gfdc_auth_system_info', rel: 'n-1' }, inverseSide: { label: '系统菜单', prop: 'RESOURCE' } },
    { prop: 'RESOURCE_URL' },
    { prop: 'RESOURCE_DESC' },
    { prop: 'RESOURCE_TYPE', options: [{ label: '菜单', value: 1 }, { label: '按钮', value: 2 }] },
    { prop: 'OPEN_TYPE', options: [{ label: '菜单', value: 0 }, { label: 'iframe', value: 1 }] },
    { prop: 'EXT_URL' },
    { prop: 'EXT_PARAMS' },
    { prop: 'RESOURCE_LEVEL' },
    { prop: 'SORT_TYPE' },
    { prop: 'PARENT', relation: { table: 'gfdc_auth_resource', rel: 'n-1' }, inverseSide: { label: '菜单', prop: 'CHILDREN' } },
    { prop: 'COMPONENT' },
    { prop: 'ICON_TYPE' },
    { prop: 'ICON' },
    { prop: 'IDENTIFY' },
    { prop: 'LEAF' },
    { prop: 'HIDDEN', options: [{ label: '否', value: 0 }, { label: '是', value: 1 }] },
    { prop: 'IF_CACHE', options: [{ label: '否', value: 0 }, { label: '是', value: 1 }] },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['RESOURCE_NAME', 'RESOURCE_CODE', 'SYSTEM', 'RESOURCE_URL', 'COMPONENT', 'RESOURCE_TYPE', 'OPEN_TYPE', 'EXT_URL', 'EXT_PARAMS', 'PARENT', 'HIDDEN', 'IF_CACHE'],
  searchs: ['PARENT', 'ROLE_RESOURCE.ROLE'],
  forms: ['RESOURCE_NAME', 'RESOURCE_CODE', 'SYSTEM', 'PARENT', 'RESOURCE_URL', 'COMPONENT', 'RESOURCE_TYPE', 'OPEN_TYPE', 'EXT_URL', 'EXT_PARAMS', 'RESOURCE_LEVEL', 'ICON_TYPE', 'ICON', 'HIDDEN', 'IF_CACHE', 'ROLE_RESOURCE.ROLE'],
  map: { label: 'RESOURCE_NAME', id: 'ID' },
}

export const gfdc_auth_role_resource: TableOpt = {
  label: '_角色资源',
  fields: [
    { prop: 'ID' },
    { prop: 'ROLE', relation: { table: 'gfdc_auth_role', rel: 'n-1' }, inverseSide: { label: '资源', prop: 'ROLE_RESOURCE' } },
    { prop: 'RESOURCE', relation: { table: 'gfdc_auth_resource', rel: 'n-1' }, inverseSide: { label: '角色', prop: 'ROLE_RESOURCE' } },
  ],
  middle: true,
  map: { id: 'ID' },
}

export const gfdc_auth_system_info: TableOpt = {
  label: '系统',
  fields: [
    { prop: 'ID' },
    { prop: 'SYSTEM_NAME' },
    { prop: 'SYSTEM_CODE' },
    { prop: 'SYSTEM_DESC' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['SYSTEM_NAME', 'SYSTEM_CODE', 'SYSTEM_DESC', 'CREATOR', 'CREATE_TIME'],
  forms: ['SYSTEM_NAME', 'SYSTEM_CODE', 'SYSTEM_DESC'],
  map: { label: 'SYSTEM_NAME', id: 'ID' },
}

export const gfdc_auth_sys_operation_log: TableOpt = {
  label: '操作日志',
  fields: [
    { prop: 'ID' },
    { label: '系统', prop: 'SYSTEM_CODE' },
    { label: '模块', prop: 'MODULE_NAME' },
    { label: 'ip', prop: 'REMOTE_ADDR' },
    { label: '操作人', prop: 'USER', relation: { table: 'gfdc_auth_user', rel: 'n-1' }, inverseSide: { label: '操作日志', prop: 'SYS_OPERATION_LOG' } },
    { prop: 'USER_ACCOUNT' },
    { label: '描述', prop: 'OPERATION_DESC', filter: 'contains' },
    { prop: 'REQUEST_URI' },
    { prop: 'REQUEST_TYPE' },
    { prop: 'REQUEST_PARAMS' },
    { prop: 'EXEC_STATUS', options: [{ label: '失败', value: 0 }, { label: '成功', value: 1 }] },
    { prop: 'RUNTIME' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['MODULE_NAME', 'OPERATION_DESC', 'USER', 'REMOTE_ADDR', 'REQUEST_URI', 'EXEC_STATUS', 'RUNTIME', 'CREATE_TIME'],
  forms: ['MODULE_NAME', 'OPERATION_DESC', 'USER', 'REMOTE_ADDR', 'REQUEST_URI', 'EXEC_STATUS', 'RUNTIME'],
  views: ['MODULE_NAME', 'OPERATION_DESC', 'USER', 'REMOTE_ADDR', 'REQUEST_URI', 'EXEC_STATUS', 'RUNTIME', 'REQUEST_PARAMS'],
  searchs: ['MODULE_NAME', 'OPERATION_DESC', 'USER'],
  map: { label: 'OPERATION_DESC', id: 'ID' },
}

export const gfdc_guide_config: TableOpt = {
  label: '常见配置',
  fields: [
    { prop: 'ID' },
    { prop: 'SYSTEM_CODE' },
    { prop: 'EFFECTIVE_SCOPE', options: [{ label: '产品指南', value: 'SystemGuide' }, { label: '操作指南', value: 'BiGuide' }, { label: '常见问题', value: 'QuestionNormally' }] },
    { prop: 'TITLE', filter: 'contains' },
    { prop: 'ICON' },
    { prop: 'CONTENT', editor: { type: 'textarea', autosize: { minRows: 4 } } },
    { prop: 'IF_VALID', options: [{ label: '失效', value: 0 }, { label: '有效', value: 1 }] },
    { prop: 'SORT' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['SYSTEM_CODE', 'EFFECTIVE_SCOPE', 'TITLE', 'SORT'],
  forms: ['SYSTEM_CODE', 'EFFECTIVE_SCOPE', 'TITLE', 'CONTENT'],
  searchs: ['SYSTEM_CODE', 'EFFECTIVE_SCOPE', 'TITLE'],
  map: { label: 'TITLE', id: 'ID' },
}

export const gfdc_message_object: TableOpt = {
  label: '消息中心',
  fields: [
    { prop: 'ID' },
    { prop: 'MESSAGE_NAME' },
    { prop: 'MESSAGE_CODE' },
    { prop: 'TYPE' },
    { prop: 'TITLE' },
    { prop: 'MESSAGE' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
    { prop: 'start_time' },
    { prop: 'end_time' },
  ],
  columns: ['MESSAGE_NAME', 'MESSAGE_CODE', 'TYPE', 'CREATOR', 'CREATE_TIME'],
  // forms: ['MESSAGE_NAME', 'MESSAGE_CODE', 'TYPE'],
  // searchs: ['MESSAGE_NAME', 'MESSAGE_CODE'],
  map: { label: 'MESSAGE_NAME', id: 'ID' },
}

export const gfdc_message_task: TableOpt = {
  label: '消息任务',
  fields: [
    { prop: 'ID' },
    { prop: 'JOB_NAME' }, // TODO 关联 MESSAGE_CODE
    { prop: 'DESCRIPTION' },
    { prop: 'CRON_EXPRESSION' },
    { prop: 'BEAN_CLASS' },
    { prop: 'METHOD_NAME' },
    { prop: 'JOB_STATUS', options: [{ label: '禁用', value: 0 }, { label: '启用', value: 1 }] },
    { prop: 'PARAMS' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['JOB_NAME', 'DESCRIPTION', 'BEAN_CLASS', 'METHOD_NAME', 'JOB_STATUS'],
  map: { label: 'JOB_NAME', id: 'ID' },
}

export const gfdc_sjkd_data_model: TableOpt = {
  label: '数据模型',
  fields: [
    { prop: 'ID' },
    { prop: 'MODEL_CODE' },
    { prop: 'MODEL_NAME', filter: 'contains' },
    { prop: 'DATA_FORM_JSON' },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['MODEL_NAME', 'MODEL_CODE', 'DATA_MODEL_RESOURCE.RESOURCE', 'MODEL_NAME', 'CREATOR'],
  forms: ['MODEL_NAME'],
  searchs: ['MODEL_NAME', 'MODEL_CODE', 'DATA_MODEL_RESOURCE.RESOURCE'],
  map: { label: 'MODEL_NAME', id: 'ID' },
}

export const gfdc_sjkd_data_model_resource: TableOpt = {
  label: '数据模型资源',
  fields: [
    { prop: 'ID' },
    { prop: 'DATA_MODEL', relation: { table: 'gfdc_sjkd_data_model', rel: 'n-1' }, inverseSide: { label: '资源', prop: 'DATA_MODEL_RESOURCE' } },
    { prop: 'RESOURCE', relation: { table: 'gfdc_auth_resource', rel: 'n-1' }, inverseSide: { label: '数据模型', prop: 'DATA_MODEL_RESOURCE' } },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  middle: true,
  map: { id: 'ID' },
}

export const gfdc_auth_dictionary: TableOpt = {
  label: '字典',
  fields: [
    { prop: 'ID' },
    { prop: 'DICT_CODE' },
    { prop: 'DICT_NAME' },
    { prop: 'DICT_NAME_EN' },
    { prop: 'DESCRIPTION' },
    { prop: 'ORDER_NUM' },
    { prop: 'USE_STATE', options: [{ label: '禁用', value: 0 }, { label: '启用', value: 1 }] },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['DICT_NAME', 'DICT_CODE', 'DICT_NAME_EN', 'DESCRIPTION', 'ORDER_NUM', 'USE_STATE', 'ITEMS'],
  forms: ['DICT_CODE', 'DICT_NAME', 'DICT_NAME_EN', 'DESCRIPTION', 'ORDER_NUM', 'USE_STATE'],
  searchs: ['DICT_CODE', 'DICT_NAME', 'USE_STATE'],
  map: { label: 'DICT_NAME', id: 'ID' }
}

export const gfdc_auth_dictionary_item: TableOpt = {
  label: '字典 Item',
  fields: [
    { prop: 'ID' },
    { prop: 'DICTIONARY', relation: { table: 'gfdc_auth_dictionary', rel: 'n-1' }, inverseSide: { label: '字典 Item', prop: 'ITEMS' } },
    { prop: 'ITEM_NAME' },
    { prop: 'ITEM_NAME_EN' },
    { prop: 'ITEM_VALUE' },
    { prop: 'DESCRIPTION' },
    { prop: 'ORDER_NUM' },
    { prop: 'ITEM_STATE', options: [{ label: '禁用', value: 0 }, { label: '启用', value: 1 }] },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  columns: ['DICTIONARY', 'ITEM_NAME', 'ITEM_NAME_EN', 'ITEM_VALUE', 'DESCRIPTION', 'ORDER_NUM', 'ITEM_STATE'],
  forms: ['DICTIONARY', 'ITEM_NAME', 'ITEM_NAME_EN', 'ITEM_VALUE', 'DESCRIPTION', 'ORDER_NUM', 'ITEM_STATE'],
  searchs: ['DICTIONARY', 'ITEM_NAME', 'ITEM_NAME_EN'],
  map: { label: 'ITEM_NAME', id: 'ID' }
}

export const gfdc_report_ds: TableOpt = {
  label: '数据源',
  fields: [
    { label: '主键', prop: 'ID' },
    { label: '名称', prop: 'DS_NAME', filter: 'contains' },
    { label: '类型', prop: 'DS_TYPE' },
    { label: '驱动类路径', prop: 'DS_DRIVER' },
    { label: '地址', prop: 'DS_HOST' },
    { label: '端口号', prop: 'DS_PORT' },
    { label: 'url', prop: 'DS_URL' },
    { label: '账号', prop: 'USERNAME' },
    { label: '密码', prop: 'PASSWORD' },
    { label: '是否启用', prop: 'VALID', options: [{ label: '禁用', value: 0 }, { label: '启用', value: 1 }] },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '逻辑删除', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'version' },
  ],
  columns: ['DS_NAME', 'DS_TYPE', 'DS_DRIVER', 'DS_URL', 'USERNAME', 'VALID'],
  forms: ['DS_NAME', 'DS_TYPE', 'DS_DRIVER', 'DS_HOST', 'DS_PORT', 'DS_URL', 'USERNAME', 'PASSWORD', 'VALID'],
  searchs: ['DS_NAME', 'DS_TYPE', 'VALID'],
  map: { label: 'DS_NAME', id: 'ID' }
}

export const gfdc_report_dataset: TableOpt = {
  label: '数据集',
  fields: [
    { label: '主键', prop: 'ID' },
    { label: '数据集类型', prop: 'DATASET_TYPE' },
    { label: '数据集名称', prop: 'DATASET_NAME', filter: 'contains' },
    { label: '查询语句', prop: 'DATASET_SQL' }, // todo textarea
    { label: '查询条件', prop: 'PARAMETERS' },
    { label: '数据源', prop: 'DS', relation: { table: 'gfdc_report_ds', rel: 'n-1' }, inverseSide: { label: '数据集', prop: 'DATASET' } },
    { label: '是否启用', prop: 'VALID', options: [{ label: '禁用', value: 0 }, { label: '启用', value: 1 }] },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '逻辑删除', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'version' },
  ],
  columns: ['DATASET_NAME', 'DATASET_TYPE', 'PARAMETERS', 'DS', 'VALID'],
  forms: ['DATASET_NAME', 'DATASET_TYPE', 'DATASET_SQL', 'PARAMETERS', 'DS', 'VALID'],
  searchs: ['DATASET_NAME', 'DATASET_TYPE', 'DS', 'VALID'],
  map: { label: 'DATASET_NAME', id: 'ID' }
}

export const gfdc_indicator_library: TableOpt = {
  label: '指标库',
  fields: [
    { label: '主键', prop: 'ID' },
    { label: '指标英文编码', prop: 'INDICATOR_CODE', filter: 'contains' },
    { label: '指标中文名称', prop: 'INDICATOR_NAME', filter: 'contains' },
    { label: '指标类型', prop: 'INDICATOR_TYPE' },
    { label: '指标描述', prop: 'INDICATOR_DESC' },
    { label: '业务逻辑', prop: 'BUSINESS_LOGIC' },
    { label: '业务OWNER', prop: 'BUSINESS_OWNER' },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '否', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'version' },
  ],
  columns: ['INDICATOR_CODE', 'INDICATOR_NAME', 'INDICATOR_TYPE', 'INDICATOR_DESC', 'BUSINESS_LOGIC', 'BUSINESS_OWNER', 'CREATOR', 'CREATE_TIME', 'MODIFIER', 'MODIFY_TIME'],
  forms: ['INDICATOR_CODE', 'INDICATOR_NAME', 'INDICATOR_TYPE', 'INDICATOR_DESC', 'BUSINESS_LOGIC', 'BUSINESS_OWNER'],
  searchs: ['INDICATOR_CODE', 'INDICATOR_NAME', 'INDICATOR_TYPE'],
  map: { label: 'INDICATOR_NAME', id: 'ID' }
}

export const gfdc_target_head: TableOpt = {
  label: '目标值抬头',
  fields: [
    { label: '主键', prop: 'ID' },
    { label: '目标值编码', prop: 'TARGET_CODE', filter: 'contains' },
    { label: '目标值名称', prop: 'TARGET_NAME', filter: 'contains' },
    { label: '是否启用目标值', prop: 'TARGET_ENABLE' },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '逻辑删除', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'version' },
  ],
  columns: ['TARGET_CODE', 'TARGET_NAME', 'TARGET_ENABLE', 'CREATOR', 'CREATE_TIME', 'MODIFIER', 'MODIFY_TIME'],
  forms: ['TARGET_CODE', 'TARGET_NAME', 'TARGET_ENABLE', 'CREATOR', 'CREATE_TIME', 'MODIFIER', 'MODIFY_TIME'],
  searchs: ['TARGET_CODE', 'TARGET_NAME'],
  map: { label: 'TARGET_NAME', id: 'ID' }
}

export const gfdc_target_config: TableOpt = {
  label: '目标值字段',
  fields: [
    { label: '主键', prop: 'ID' },
    { label: '字段编码', prop: 'FIELD_CODE', filter: 'contains' },
    { label: '字段名称', prop: 'FIELD_NAME', filter: 'contains' },
    { label: '字段类型', prop: 'FIELD_TYPE' },
    { label: '是否必填', prop: 'REQUIRED' },
    { label: '关联目标值', prop: 'RELATION_TARGET_HEAD', relation: { table: 'gfdc_target_head', rel: 'n-1' }, inverseSide: { label: '关联字段', prop: 'RELATION_FIELDS' } },
    { label: '备注', prop: 'REMARK' },
    { label: '目标值抬头', prop: 'TARGET_HEAD', relation: { table: 'gfdc_target_head', rel: 'n-1' }, inverseSide: { label: '字段', prop: 'FIELDS' } },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '逻辑删除', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'version' },
  ],
  columns: ['FIELD_CODE', 'FIELD_NAME', 'FIELD_TYPE', 'REQUIRED', 'RELATION_TARGET_HEAD', 'REMARK', 'TARGET_HEAD', 'CREATOR', 'CREATE_TIME', 'MODIFIER', 'MODIFY_TIME'],
  forms: ['FIELD_CODE', 'FIELD_NAME', 'FIELD_TYPE', 'REQUIRED', 'RELATION_TARGET_HEAD', 'REMARK', 'TARGET_HEAD'],
  searchs: ['FIELD_CODE', 'FIELD_NAME', 'FIELD_TYPE', 'RELATION_TARGET_HEAD', 'TARGET_HEAD'],
  map: { label: 'FIELD_NAME', id: 'ID' }
}

export const gfdc_target_config_item: TableOpt = {
  label: '目标值数据',
  fields: [
    { label: '主键', prop: 'ID' },
    { label: '目标值抬头', prop: 'TARGET_HEAD', relation: { table: 'gfdc_target_head', rel: 'n-1' }, inverseSide: { label: '数据', prop: 'ITEMS' } },
    { label: '目标值字段', prop: 'TARGET_CONFIG', relation: { table: 'gfdc_target_config', rel: 'n-1' }, inverseSide: { label: '数据', prop: 'ITEMS' } },
    // { label: '目标值明细ID', prop: 'TARGET_ITEM', relation: { table: 'gfdc_target_config', rel: 'n-1' }, inverseSide: { label: '数据', prop: 'ITEMS' } },
    { label: '值', prop: 'FIELD_VALUE' },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '逻辑删除', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'version' },
  ],
  columns: ['TARGET_HEAD', 'TARGET_CONFIG', 'FIELD_VALUE', 'CREATOR', 'CREATE_TIME', 'MODIFIER', 'MODIFY_TIME'],
  forms: ['TARGET_HEAD', 'TARGET_CONFIG', 'FIELD_VALUE'],
  searchs: ['TARGET_HEAD', 'TARGET_CONFIG', 'FIELD_VALUE'],
  map: { id: 'ID' }
}

export const gfdc_service_list: TableOpt = {
  label: '服务列表',
  fields: [
    { label: 'ID', prop: 'ID' },
    { label: '模块', prop: 'MODULE' },
    { label: '菜单', prop: 'RESOURCE', relation: { table: 'gfdc_auth_resource', rel: 'n-1' }, inverseSide: { label: '服务列表', prop: 'SL' } },
    { label: '菜单释义', prop: 'RESOURCE_DEFINE', filter: 'contains' },
    { label: '时效', prop: 'AGEING' },
    { label: '排序', prop: 'SORT' },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '逻辑删除', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'VERSION' },
  ],
  columns: ['RESOURCE.SYSTEM', 'RESOURCE', 'RESOURCE_DEFINE', 'AGEING', 'MODULE', 'SORT', 'SL_INDICATOR.INDICATOR_DEFINE'],
  forms: ['RESOURCE', 'RESOURCE_DEFINE', 'AGEING', 'MODULE', 'SORT'],
  searchs: ['MODULE', 'RESOURCE', 'RESOURCE_DEFINE'],
  map: { label: 'RESOURCE_DEFINE', id: 'ID' }
}

export const gfdc_service_list_indicator_define: TableOpt = {
  label: '服务指标',
  fields: [
    { prop: 'ID' },
    { prop: 'SERVICE_LIST', relation: { table: 'gfdc_service_list', rel: 'n-1' }, inverseSide: { label: '服务指标', prop: 'SL_INDICATOR' } },
    { prop: 'INDICATOR_DEFINE', relation: { table: 'gfdc_indicator_define', rel: 'n-1' }, inverseSide: { label: '服务指标', prop: 'SL_INDICATOR' } },
    { prop: 'CREATOR_NO' },
    { prop: 'CREATOR' },
    { prop: 'CREATE_TIME' },
    { prop: 'MODIFIER_NO' },
    { prop: 'MODIFIER' },
    { prop: 'MODIFY_TIME' },
    { prop: 'DEL_FLAG' },
    { prop: 'VERSION' },
  ],
  middle: true,
  map: { id: 'ID' }
}

export const gfdc_indicator_define: TableOpt = {
  label: '指标定义',
  fields: [
    { label: 'ID', prop: 'ID' },
    { label: '指标名称', prop: 'INDICATOR_NAME', filter: 'contains' },
    { label: '计算逻辑', prop: 'CALCULATE_LOGIC', filter: 'contains' },
    { label: '数据来源', prop: 'DATA_SOURCE', filter: 'contains' },
    { label: '业务owner', prop: 'BUZ_OWNER', filter: 'contains' },
    { label: '排序', prop: 'SORT' },
    { label: '创建人工号', prop: 'CREATOR_NO' },
    { label: '创建人', prop: 'CREATOR' },
    { label: '创建时间', prop: 'CREATE_TIME' },
    { label: '修改人工号', prop: 'MODIFIER_NO' },
    { label: '修改人', prop: 'MODIFIER' },
    { label: '修改时间', prop: 'MODIFY_TIME' },
    { label: '逻辑删除', prop: 'DEL_FLAG' },
    { label: '乐观锁', prop: 'VERSION' },
  ],
  columns: ['INDICATOR_NAME', 'CALCULATE_LOGIC', 'DATA_SOURCE', 'BUZ_OWNER', 'SL_INDICATOR.SERVICE_LIST', 'SORT'],
  forms: ['INDICATOR_NAME', 'CALCULATE_LOGIC', 'DATA_SOURCE', 'BUZ_OWNER', 'SORT'],
  searchs: ['INDICATOR_NAME', 'CALCULATE_LOGIC', 'DATA_SOURCE', 'BUZ_OWNER'],
  map: { label: 'INDICATOR_NAME', id: 'ID' }
}